# Generated by Django 3.1.2 on 2020-10-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoblog', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
