# Generated by Django 3.1.2 on 2020-11-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoblog', '0003_auto_20201031_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
