# Generated by Django 3.1.2 on 2020-11-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoblog', '0004_auto_20201102_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
