# Generated by Django 3.1.2 on 2020-11-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoblog', '0005_auto_20201102_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='me', max_length=200),
        ),
    ]
