# Generated by Django 3.1.2 on 2020-11-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoblog', '0008_auto_20201108_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='you', max_length=200),
        ),
    ]
