# Generated by Django 3.1.2 on 2020-11-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoblog', '0011_auto_20201108_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
