# Generated by Django 3.1.2 on 2020-11-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoblog', '0013_auto_20201110_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prefazione',
            field=models.CharField(default='sasà ', max_length=255),
        ),
    ]
