# Generated by Django 3.1.2 on 2020-11-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoblog', '0014_post_prefazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='prefazione',
            field=models.CharField(max_length=255),
        ),
    ]
